services:
  db:
    image: postgres
    container_name: "db"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=qwerty"
      - "POSTGRES_DB=pd311_web_api"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - api_nt

  api:
    image: potapchuk22/pd311_api
    container_name: "api"
    ports:
      - "80:8080"
    environment:
      - ConnectionStrings__NpgsqlLocal=User ID=postgres;Password=qwerty;Host=db;Port=5432;Database=pd311_web_api;
    depends_on:
      db:
        condition: service_healthy
    networks:
          - api_nt

networks:
  api_nt:
